# Site settings
title: Abraham Ashade's Portfolio
email: Ashmark.abra@gmail.com
url: https://abr9h9m.github.io/Abraham-s-portfolio.github.io/
description: "This website will be about my journey through college as a Computer Science Scholar, it will include my projects, Computing languages and so on."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Abraham's Website 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/Abr9h9m

# Build settings
markdown: kramdown
permalink: pretty
